DROP TABLE IF EXISTS CODE_DEFINITION;
DROP TABLE IF EXISTS CODE_CATEGORY;
CREATE TABLE IF NOT EXISTS CODE_CATEGORY (
  CODE_CATEGORY_PK NUMBER(10) NOT NULL AUTO_INCREMENT,
  CATEGORY VARCHAR (255)
);
ALTER TABLE CODE_CATEGORY ADD PRIMARY KEY (CODE_CATEGORY_PK);
ALTER TABLE CODE_CATEGORY ALTER COLUMN CODE_CATEGORY_PK RESTART WITH 100;
ALTER TABLE CODE_CATEGORY ADD CONSTRAINT IF NOT EXISTS CODE_CATEGORY_CODE_UNQ UNIQUE(CATEGORY);
CREATE INDEX IF NOT EXISTS CODE_CATEGORY_CODE_IDX ON CODE_CATEGORY (CATEGORY);


CREATE TABLE IF NOT EXISTS CODE_DEFINITION (
  CODE_DEFINITION_PK NUMBER(10) NOT NULL AUTO_INCREMENT,
  CODE_CATEGORY_PK NUMBER(10) NOT NULL,
  CODE NUMBER(10),
  DEFINITION VARCHAR (255)
);
ALTER TABLE CODE_DEFINITION ADD PRIMARY KEY (CODE_DEFINITION_PK);
ALTER TABLE CODE_DEFINITION ALTER COLUMN CODE_DEFINITION_PK RESTART WITH 100;
ALTER TABLE CODE_DEFINITION ADD CONSTRAINT IF NOT EXISTS CODE_CATEGORY_CODE_UNQ UNIQUE(CODE_CATEGORY_PK, CODE);
CREATE INDEX IF NOT EXISTS CODE_DEFINITION_CATEGORY_IDX ON CODE_DEFINITION (CODE_CATEGORY_PK);
CREATE INDEX IF NOT EXISTS CODE_DEFINITION_CODE_IDX ON CODE_DEFINITION (CODE_CATEGORY_PK, CODE);
CREATE INDEX IF NOT EXISTS CODE_DEFINITION_DEFIN_IDX ON CODE_DEFINITION (CODE_CATEGORY_PK, DEFINITION);

CREATE TABLE IF NOT EXISTS CONFLICT (
  GWNO NUMBER(10) NOT NULL,
  EVENT_ID_CNTY VARCHAR (15) NOT NULL,
  EVENT_ID_NO_CNTY NUMBER(10) NOT NULL,
  EVENT_DATE VARCHAR (15) NOT NULL,
  YEAR NUMBER(10) NOT NULL,
  TIME_PRECISION NUMBER(10) NOT NULL,
  EVENT_TYPE VARCHAR (100) NOT NULL,
  ACTOR1 VARCHAR (1000),
  ALLY_ACTOR_1 VARCHAR (1000),
  INTER1 NUMBER(10) NOT NULL,
  ACTOR2 VARCHAR (1000),
  ALLY_ACTOR_2 VARCHAR (1000),
  INTER2 NUMBER(10) NOT NULL,
  INTERACTION NUMBER(10) NOT NULL,
  COUNTRY VARCHAR (100) NOT NULL,
  COUNTRY_LOWERCASE VARCHAR (100) AS LOWER(COUNTRY),
  ADMIN1 VARCHAR (100),
  ADMIN1_LOWERCASE VARCHAR (100) AS LOWER(ADMIN1),
  ADMIN2 VARCHAR (100),
  ADMIN3 VARCHAR (100),
  LOCATION VARCHAR (100) NOT NULL,
  LATITUDE DOUBLE NOT NULL,
  LONGITUDE DOUBLE NOT NULL,
  GEO_PRECIS NUMBER(10) NOT NULL,
  SOURCE VARCHAR (1000),
  NOTES VARCHAR (2000),
  FATALITIES NUMBER(10)
);
ALTER TABLE CONFLICT ADD PRIMARY KEY (EVENT_ID_NO_CNTY);
CREATE INDEX IF NOT EXISTS CONFLICT_COUNTRY_IDX ON CONFLICT(COUNTRY_LOWERCASE);
CREATE INDEX IF NOT EXISTS CONFLICT_EVENT_TYPE_IDX ON CONFLICT(EVENT_TYPE);
CREATE INDEX IF NOT EXISTS CONFLICT_LOCATION_IDX ON CONFLICT(LOCATION);
CREATE INDEX IF NOT EXISTS CONFLICT_ACTOR1_IDX ON CONFLICT(ACTOR1);
CREATE INDEX IF NOT EXISTS CONFLICT_ACTOR2_IDX ON CONFLICT(ACTOR2);
CREATE INDEX IF NOT EXISTS CONFLICT_COUNTRY_ADMIN1_IDX ON CONFLICT(COUNTRY_LOWERCASE, ADMIN1_LOWERCASE);


